version: "3.9"

services:
  # A customized instance of collectivo for MILA.
  collectivo:
    restart: always
    build: ./collectivo
    volumes:
      - ./collectivo/collectivo.yml:/collectivo_app/collectivo.yml
      - ./collectivo/extensions/mila:/collectivo_app/mila
      - ./docker/static:/app/static
    command: >
      sh -c "while ! nc -z collectivo-db 5432; do sleep 1; done &&
             while ! nc -z keycloak 8080; do sleep 1; done &&
             python manage.py migrate &&
             gunicorn collectivo_app.wsgi:application --bind 0.0.0.0:8000
             "
    environment:
      DB_HOST: collectivo-db
      DB_NAME: collectivo_db
      DB_USER: ${COLLECTIVO_DB_USER}
      DB_PASS: ${COLLECTIVO_DB_PASSWORD}
      SECRET_KEY: ${COLLECTIVO_SECRET_KEY}
      ALLOWED_HOSTS: ${COLLECTIVO_URL}
      ALLOWED_ORIGINS: ${COLLECTIVO_UX_URL}
      KEYCLOAK_URL: ${KEYCLOAK_URL}
      KEYCLOAK_CLIENT_SECRET: ${COLLECTIVO_KEYCLOAK_CLIENT_SECRET_KEY}
      EMAIL_HOST: ${EMAIL_HOST}
      EMAIL_PORT: ${EMAIL_PORT}
      EMAIL_USE_SSL: ${EMAIL_USE_SSL}
      EMAIL_USE_TLS: ${EMAIL_USE_TLS}
      EMAIL_FROM: ${EMAIL_FROM}
      EMAIL_HOST_USER: ${EMAIL_HOST_USER}
      EMAIL_HOST_PASSWORD: ${EMAIL_HOST_PASSWORD}
      CELERY_BROKER: "redis://:${REDIS_PASSWORD}@redis:6379/0"
      CELERY_BACKEND: "redis://:${REDIS_PASSWORD}@redis:6379/0"
      DIREKTKREDIT_SERVER_URL: ${HABIDAT_SERVER_URL}
      LOTZAPP_URL: "${LOTZAPP_URL}"
      LOTZAPP_USER: "${LOTZAPP_USER}"
      LOTZAPP_PASS: "${LOTZAPP_PASS}"
      VIRTUAL_HOST: ${COLLECTIVO_URL}
      VIRTUAL_PORT: 8000
      LETSENCRYPT_HOST: ${COLLECTIVO_URL}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
    labels:
      io.portainer.accesscontrol.teams: mila
    depends_on:
      - collectivo-db
      - keycloak
      - redis
    links:
      - keycloak

  # A celery worker that runs in the background.
  # Image & environment should be the same as collectivo-mila.
  celery:
    restart: always
    build: ./collectivo
    command: celery -A collectivo_app worker -l info
    volumes:
      - ./collectivo/collectivo.yml:/collectivo_app/collectivo.yml
      - ./docker/static:/app/static
    environment:
      DB_HOST: collectivo-db
      DB_NAME: collectivo_db
      DB_USER: ${COLLECTIVO_DB_USER}
      DB_PASS: ${COLLECTIVO_DB_PASSWORD}
      SECRET_KEY: ${COLLECTIVO_SECRET_KEY}
      ALLOWED_HOSTS: ${COLLECTIVO_URL}
      ALLOWED_ORIGINS: ${COLLECTIVO_UX_URL}
      KEYCLOAK_URL: ${KEYCLOAK_URL}
      KEYCLOAK_CLIENT_SECRET: ${COLLECTIVO_KEYCLOAK_CLIENT_SECRET_KEY}
      EMAIL_HOST: ${EMAIL_HOST}
      EMAIL_PORT: ${EMAIL_PORT}
      EMAIL_USE_SSL: ${EMAIL_USE_SSL}
      EMAIL_USE_TLS: ${EMAIL_USE_TLS}
      EMAIL_FROM: ${EMAIL_FROM}
      EMAIL_HOST_USER: ${EMAIL_HOST_USER}
      EMAIL_HOST_PASSWORD: ${EMAIL_HOST_PASSWORD}
      CELERY_BROKER: "redis://:${REDIS_PASSWORD}@redis:6379/0"
      CELERY_BACKEND: "redis://:${REDIS_PASSWORD}@redis:6379/0"
      DIREKTKREDIT_SERVER_URL: ${HABIDAT_SERVER_URL}
      LOTZAPP_URL: "${LOTZAPP_URL}"
      LOTZAPP_USER: "${LOTZAPP_USER}"
      LOTZAPP_PASS: "${LOTZAPP_PASS}"
      VIRTUAL_HOST: ${COLLECTIVO_URL}
      VIRTUAL_PORT: 8000
      LETSENCRYPT_HOST: ${COLLECTIVO_URL}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
    labels:
      io.portainer.accesscontrol.teams: mila
    depends_on:
      - collectivo
      - redis

  # A celery worker that runs in the background and processes the scheduled tasks.
  celery-beat:
    restart: always
    build: ./collectivo
    command: celery -A collectivo_app beat -l info
    volumes:
      - ./collectivo/collectivo.yml:/collectivo_app/collectivo.yml
      - ./docker/static:/app/static
    environment:
      DB_HOST: collectivo-db
      DB_NAME: collectivo_db
      DB_USER: ${COLLECTIVO_DB_USER}
      DB_PASS: ${COLLECTIVO_DB_PASSWORD}
      SECRET_KEY: ${COLLECTIVO_SECRET_KEY}
      ALLOWED_HOSTS: ${COLLECTIVO_URL}
      ALLOWED_ORIGINS: ${COLLECTIVO_UX_URL}
      KEYCLOAK_URL: ${KEYCLOAK_URL}
      KEYCLOAK_CLIENT_SECRET: ${COLLECTIVO_KEYCLOAK_CLIENT_SECRET_KEY}
      EMAIL_HOST: ${EMAIL_HOST}
      EMAIL_PORT: ${EMAIL_PORT}
      EMAIL_USE_SSL: ${EMAIL_USE_SSL}
      EMAIL_USE_TLS: ${EMAIL_USE_TLS}
      EMAIL_FROM: ${EMAIL_FROM}
      EMAIL_HOST_USER: ${EMAIL_HOST_USER}
      EMAIL_HOST_PASSWORD: ${EMAIL_HOST_PASSWORD}
      CELERY_BROKER: "redis://:${REDIS_PASSWORD}@redis:6379/0"
      CELERY_BACKEND: "redis://:${REDIS_PASSWORD}@redis:6379/0"
      DIREKTKREDIT_SERVER_URL: ${HABIDAT_SERVER_URL}
      LOTZAPP_URL: "${LOTZAPP_URL}"
      LOTZAPP_USER: "${LOTZAPP_USER}"
      LOTZAPP_PASS: "${LOTZAPP_PASS}"
      VIRTUAL_HOST: ${COLLECTIVO_URL}
      VIRTUAL_PORT: 8000
      LETSENCRYPT_HOST: ${COLLECTIVO_URL}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
    labels:
      io.portainer.accesscontrol.teams: mila
    depends_on:
      - collectivo
      - redis

  # A communication broker for celery.
  redis:
    image: redis:7.0-alpine
    command: >
      --requirepass "${REDIS_PASSWORD}" --appendonly yes --maxmemory 1000mb
      --maxmemory-policy volatile-lru
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
    deploy:
      resources:
        limits:
          memory: 1024M
    labels:
      io.portainer.accesscontrol.teams: mila

  # A static files server for django.
  collectivo-static:
    image: nginx:alpine
    volumes:
      - ./docker/static:/app/static
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
      - ./docker/nginx/error.html:/usr/share/nginx/html/index.html
    restart: always
    labels:
      io.portainer.accesscontrol.teams: mila

  # A PostgreSQL database.
  collectivo-db:
    image: postgres:14-alpine
    volumes:
      - collectivo-db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: collectivo_db
      POSTGRES_USER: ${COLLECTIVO_DB_USER}
      POSTGRES_PASSWORD: ${COLLECTIVO_DB_PASSWORD}
    labels:
      io.portainer.accesscontrol.teams: mila

  # A frontend web application.
  collectivo-ux:
    build: ./collectivo-ux
    restart: always
    environment:
      VIRTUAL_HOST: ${COLLECTIVO_UX_URL}
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: ${COLLECTIVO_UX_URL}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
      VITE_API_URL: ${COLLECTIVO_URL}
      VITE_KEYCLOAK_URL: ${KEYCLOAK_URL}
    labels:
      io.portainer.accesscontrol.teams: mila

  # Database for keycloak
  keycloak-db:
    image: postgres:14-alpine
    volumes:
      - keycloak-db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: ${KEYCLOAK_DB_USER}
      POSTGRES_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
    labels:
      io.portainer.accesscontrol.teams: mila

  # Keycloak for authentication.
  keycloak:
    build: ./docker/keycloak
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KEYCLOAK_FRONTEND_URL: ${KEYCLOAK_URL}
      KEYCLOAK_IMPORT: /tmp/collectivo-realm.json
      KC_DB_USERNAME: ${KEYCLOAK_DB_USER}
      KC_DB_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
      KC_DB_SCHEMA: public
      KC_DB_URL_DATABASE: ${KEYCLOAK_DB_NAME}
      KC_DB_URL_HOST: ${KEYCLOAK_DB_HOST}
      KC_DB_URL_PORT: 5432
      KC_HOSTNAME: ${KEYCLOAK_URL}
      VIRTUAL_HOST: ${KEYCLOAK_URL}
      VIRTUAL_PORT: 8080
      LETSENCRYPT_HOST: ${KEYCLOAK_URL}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
    volumes:
      - ./docker/keycloak/import/collectivo-realm.json:/tmp/collectivo-realm.json
      - ./docker/keycloak/themes/collectivo:/opt/keycloak/themes/collectivo
      - ./docker/keycloak/imported/:/opt/keycloak/imported/
    depends_on:
      - keycloak-db
    links:
      - keycloak-db
    labels:
      io.portainer.accesscontrol.teams: mila
  # Habidat Direktkredit Verwaltung
  habidat-db:
    image: mariadb
    restart: always
    volumes:
      - ./docker/habidat/db:/var/lib/mysql
    environment:
      - MARIADB_RANDOM_ROOT_PASSWORD=yes
      # please change:
      - MYSQL_PASSWORD=${HABIDAT_DB_SECRET}
      # no need to change for default setup:
      - MYSQL_DATABASE=${HABIDAT_DB_DB}
      - MYSQL_USER=${HABIDAT_DB_USER}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    logging:
      options:
        max-size: 50m

  habidat:
    image: habidat/direktkredit:1.1
    restart: always
    volumes:
      - ./docker/habidat/config/:/habidat/config/
      - ./docker/habidat/files:/habidat/public/files
      - ./docker/habidat/images:/habidat/public/images
      - ./docker/habidat/upload:/habidat/upload
    environment:
      - HABIDAT_DK_PROJECT_ID=project
      - HABIDAT_DK_PROJECT_NAME=Mila Wien
      - HABIDAT_DK_PROJECT_EMAIL=mitmachen@mila.wien
      - HABIDAT_DK_PROJECT_LOGO=logo.gif
      - HABIDAT_DK_ADMIN_EMAIL=mitmachen@mila.wien
      - HABIDAT_DK_ADMIN_USERNAME=${HABIDAT_ADMIN_USERNAME}
      - HABIDAT_DK_ADMIN_PASSWORD=${HABIDAT_ADMIN_SECRET}
      - HABIDAT_DK_SESSION_SECRET=${HABIDAT_JWT_SECRET}
      - HABIDAT_DK_DB_URI=mysql://${HABIDAT_DB_USER}:${HABIDAT_DB_SECRET}@habidat-db/${HABIDAT_DB_DB}
      - HABIDAT_DK_PORT_HTTP=80
      - HABIDAT_DK_AUTH_ADMIN_METHOD=local,oidc # ldap is also possible
      - HABIDAT_DK_AUTH_ADMIN_OIDC_LABEL=Mein.mila.wien Admin
      - HABIDAT_DK_AUTH_ADMIN_OIDC_ISSUER=${KEYCLOAK_URL}/realms/collectivo
      - HABIDAT_DK_AUTH_ADMIN_OIDC_CLIENT_ID=${HABIDAT_KEYCLOAK_CLIENT_ID}
      - HABIDAT_DK_AUTH_ADMIN_OIDC_CLIENT_SECRET=${HABIDAT_KEYCLOAK_TOKEN}
      - HABIDAT_DK_AUTH_ADMIN_OIDC_CALLBACK_URL=/login-oidc-cb-admin
      - HABIDAT_DK_AUTH_ADMIN_OIDC_AUTH_URL=${KEYCLOAK_URL}/realms/collectivo/protocol/openid-connect/auth
      - HABIDAT_DK_AUTH_ADMIN_OIDC_TOKEN_URL=${KEYCLOAK_URL}/realms/collectivo/protocol/openid-connect/token
      - HABIDAT_DK_AUTH_ADMIN_OIDC_USERINFO_URL=${KEYCLOAK_URL}/realms/collectivo/protocol/openid-connect/userinfo
      - HABIDAT_DK_AUTH_USER_METHOD=oidc
      - HABIDAT_DK_AUTH_USER_OIDC_LABEL=Mein.mila.wien
      - HABIDAT_DK_AUTH_USER_OIDC_ISSUER=${KEYCLOAK_URL}/realms/collectivo
      - HABIDAT_DK_AUTH_USER_OIDC_CLIENT_ID=${HABIDAT_KEYCLOAK_CLIENT_ID}
      - HABIDAT_DK_AUTH_USER_OIDC_CLIENT_SECRET=${HABIDAT_KEYCLOAK_TOKEN}
      - HABIDAT_DK_AUTH_USER_OIDC_CALLBACK_URL=/login-oidc-cb
      - HABIDAT_DK_AUTH_USER_OIDC_AUTH_URL=${KEYCLOAK_URL}/realms/collectivo/protocol/openid-connect/auth
      - HABIDAT_DK_AUTH_USER_OIDC_TOKEN_URL=${KEYCLOAK_URL}/realms/collectivo/protocol/openid-connect/token
      - HABIDAT_DK_AUTH_USER_OIDC_USERINFO_URL=${KEYCLOAK_URL}/realms/collectivo/protocol/openid-connect/userinfo
      - VIRTUAL_HOST=${HABIDAT_SERVER_URL}
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=${HABIDAT_SERVER_URL}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    depends_on:
      habidat-db:
        condition: service_healthy
    links:
      - habidat-db
    logging:
      options:
        max-size: 50m

volumes:
  collectivo-db-data:
  keycloak-db-data:
