version: "3.9"

services:

  # A customized instance of collectivo for MILA.
  # TODO LOAD INSTANCE FROM DOCKER HUB
  collectivo:
    container_name: collectivo-mila
    restart: always
    build:
      context: .
    ports:
      - "8000:8000"
    # Synchronize source code inside and outside the docker container.
    volumes:
      - ./extensions:/collectivo-app/extensions
      - ./docker/static:/app/static
    # Wait for database to be ready (this command will work only on linux),
    # migrate the database changes and start a development server.
    # TODO CHANGE TO PRODUCTION SERVER
    # TODO Is this needed if already given in dockerfile?
    command: > #
      sh -c "while ! nc -z collectivo-db 5432; do sleep 1; done &&
             while ! nc -z keycloak 8080; do sleep 1; done &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    # Environment variables
    environment:
      DB_HOST: collectivo-db
      DB_NAME: collectivo_db
      DB_USER: ${COLLECTIVO_DB_USER}
      DB_PASS: ${COLLECTIVO_DB_PASSWORD}
      SECRET_KEY: ${COLLECTIVO_SECRET_KEY}
      KEYCLOAK_CLIENT_ID: collectivo
      KEYCLOAK_REALM_NAME: collectivo
      KEYCLOAK_SERVER_URL: http://keycloak:8080  # TODO Change
      KEYCLOAK_CLIENT_SECRET_KEY: ${KEYCLOAK_CLIENT_SECRET_KEY}
      COLLECTIVO_EXTENSIONS: menus, auth, extensions, dashboard, members
      DEBUG: True
      DEVELOPMENT: True
      # Optional environment variables:
      # ALLOWED_HOSTS
      # See https://docs.djangoproject.com/en/3.2/topics/i18n/
      # LANGUAGE_CODE
      # TIME_ZONE
      # KEYCLOAK_CLIENT_ID: collectivo
      # KEYCLOAK_REALM_NAME: collectivo
    depends_on:
      - collectivo-db
      - keycloak

  collectivo-static:
    container_name: colletivo-mila-static
    image: nginx:alpine
    ports:
      - "8002:80"
    volumes:
      - ./docker/static:/app/static
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
      - ./docker/nginx/error.html:/usr/share/nginx/html/index.html
    restart: always

  # A PostgreSQL database.
  collectivo-db:
    container_name: collectivo-mila-db
    image: postgres:14-alpine
    volumes:
      - collectivo-db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: collectivo_db
      POSTGRES_USER: ${COLLECTIVO_DB_USER}
      POSTGRES_PASSWORD: ${COLLECTIVO_DB_PASSWORD}

  # A frontend web application.
  collectivo-ux:
    container_name: collectivo-mila-ux
    # TODO Change to defined docker hub image with specific version?
    build: https://github.com/MILA-Wien/collectivo-ux.git#main
    restart: always
    ports:
      - "8001:80"

  # Keycloak for authentication.
  # TODO Add a seperate database for keycloak
  # TODO Adapt for production
  keycloak:
    build: ./docker/keycloak
    container_name: collectivo-mila-keycloak
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KEYCLOAK_FRONTEND_URL: http://keycloak:8080
      ROOT_LOGLEVEL: ALL  # TODO CHange for production?
      KEYCLOAK_LOGLEVEL: DEBUG  # TODO CHange for production?
    # TODO Remove?
    volumes:
      - ./docker/keycloak/import:/opt/keycloak/data/import:ro
      - ./docker/keycloak/export:/tmp/export
    # TODO Remove? Import realm should not happen on accident and delete all users
    command:
      start-dev --import-realm
    ports:
      - "8080:8080"

volumes:
  collectivo-db-data:
