version: "3.9"

services:

  # A customized instance of collectivo for MILA.
  # TODO LOAD INSTANCE FROM DOCKER HUB
  collectivo:
    container_name: collectivo-mila
    restart: always
    image: milawien/collectivo:pr-main
    # Synchronize source code inside and outside the docker container.
    volumes:
      - ./collectivo_extensions:/collectivo-app/collectivo_extensions
      - ./docker/static:/app/static
    # Wait for database to be ready (this command will work only on linux),
    # migrate the database changes and start a development server.
    # TODO CHANGE TO PRODUCTION SERVER
    command: > #
      sh -c "while ! nc -z collectivo-db 5432; do sleep 1; done &&
             while ! nc -z keycloak 8080; do sleep 1; done &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    # Environment variables
    environment:
      DB_HOST: collectivo-db
      DB_NAME: collectivo_db
      DB_USER: ${COLLECTIVO_DB_USER}
      DB_PASS: ${COLLECTIVO_DB_PASSWORD}
      SECRET_KEY: ${COLLECTIVO_SECRET_KEY}
      KEYCLOAK_CLIENT_ID: collectivo
      KEYCLOAK_REALM_NAME: collectivo
      KEYCLOAK_SERVER_URL: ${KEYCLOAK_SERVER_URL}
      KEYCLOAK_CLIENT_SECRET_KEY: ${KEYCLOAK_CLIENT_SECRET_KEY}
      COLLECTIVO_SETTINGS: collectivo_extensions.settings
      DEBUG: False
      DEVELOPMENT: False
      # Optional environment variables:
      ALLOWED_HOSTS: collectivo.mila.wien
      # See https://docs.djangoproject.com/en/3.2/topics/i18n/
      # LANGUAGE_CODE
      # TIME_ZONE
      # KEYCLOAK_CLIENT_ID: collectivo
      # KEYCLOAK_REALM_NAME: collectivo
      VIRTUAL_HOST: collectivo.mila.wien
      VIRTUAL_PORT: 8000
      LETSENCRYPT_HOST: collectivo.mila.wien
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
    depends_on:
      - collectivo-db
      - keycloak

  collectivo-static:
    container_name: colletivo-mila-static
    image: nginx:alpine
    ports:
      - "8002:80"
    volumes:
      - ./docker/static:/app/static
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
      - ./docker/nginx/error.html:/usr/share/nginx/html/index.html
    restart: always

  nginx-proxy:
    image: nginxproxy/nginx-proxy:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/logs:/var/log/nginx
      - ./nginx/conf.d:/etc/nginx/conf.d:rw
      - ./certs:/etc/nginx/certs:ro
      - /usr/share/nginx/html
      - ./nginx/vhost.d:/etc/nginx/vhost.d:rw
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/dhparam:/etc/nginx/dhparam
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: always
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy"
  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion:dev
    container_name: letsencrypt
    volumes_from:
      - nginx-proxy
    volumes:
      - ./certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:rw

  # A PostgreSQL database.
  collectivo-db:
    container_name: collectivo-mila-db
    image: postgres:14-alpine
    volumes:
      - collectivo-db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: collectivo_db
      POSTGRES_USER: ${COLLECTIVO_DB_USER}
      POSTGRES_PASSWORD: ${COLLECTIVO_DB_PASSWORD}

  # A frontend web application.
  collectivo-ux:
    container_name: collectivo-mila-ux
    # TODO Change to defined docker hub image with specific version?
    image: milawien/collectivo-ux:latest
    restart: always
    environment:
      VIRTUAL_HOST: mein.mila.wien
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: mein.mila.wien
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
      VITE_APP_API: ${COLLECTIVO_UX_API_URL}
      VITE_KEYCLOAK_URL: ${KEYCLOAK_SERVER_URL}

  # Keycloak for authentication.
  # TODO Add a seperate database for keycloak
  # TODO Adapt for production
  keycloak:
    build: ./docker/keycloak
    container_name: collectivo-mila-keycloak
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KEYCLOAK_FRONTEND_URL: ${KEYCLOAK_SERVER_URL}
      ROOT_LOGLEVEL: ALL  # TODO CHange for production?
      KEYCLOAK_LOGLEVEL: DEBUG  # TODO CHange for production?
      VIRTUAL_HOST: login.mila.wien
      VIRTUAL_PORT: 8080
      LETSENCRYPT_HOST: login.mila.wien
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
    # TODO Remove?
    volumes:
      - ./docker/keycloak/import:/opt/keycloak/data/import:ro
      - ./docker/keycloak/export:/tmp/export
    # TODO Remove? Import realm should not happen on accident and delete all users
    command:
      start-dev --import-realm

volumes:
  collectivo-db-data:
