# Generated by Django 4.1.10 on 2023-08-16 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotzapp', '0005_alter_lotzappsync_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='lotzappaddress',
            name='sync_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='lotzappinvoice',
            name='sync_active',
            field=models.BooleanField(default=True),
        ),
    ]
