name: Collectivo-mila

# Controls when the workflow will run
on:
  workflow_call:
  push:
    tags-ignore:
      - "**"
  pull_request:
jobs:
  test-docker:
    name: Test docker environment
    runs-on: ubuntu-20.04
    steps:
      - name: Check Credentials
        run: |
          echo ${{ secrets.DOCKERHUB_USER }}
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build containers 
        run: |
          cp .env.example .env
          docker-compose up -d collectivo-db
          docker-compose build keycloak
          docker-compose up -d keycloak
          docker-compose build collectivo-ux
          docker-compose up -d collectivo-ux
          docker-compose build collectivo
      - name: Add hosts to /etc/hosts
        run: |
          sudo echo "127.0.0.1 collectivo.local" | sudo tee -a /etc/hosts
          sudo echo "127.0.0.1 keycloak" | sudo tee -a /etc/hosts
          cat /etc/hosts
          while ! curl --connect-timeout 5 -v --max-time 10 --retry 5 --retry-connrefused  --retry-delay 0 --retry-max-time 40 http://keycloak:8080
          do
              { echo "Exit status of curl: $?"
                echo "Retrying ..."
              } 1>&2
              sleep 10
          done
      - name: Test
        run: |
          docker-compose run --rm collectivo sh -c "python manage.py test && flake8"
