name: collectivo

# Controls when the workflow will run
on:
  workflow_call:
  push:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test-docker:
    name: Test docker environement
    needs: [test-python]
    runs-on: ubuntu-20.04
    steps:
      - name: Check Credentials
        run: |
          echo ${{ secrets.DOCKERHUB_USER }}
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v3
      - name: Test
        run: |
          docker-compose -f ./docker-compose-dev.yml up -d collectivo-db
          docker-compose -f ./docker-compose-dev.yml build keycloak
          docker-compose -f ./docker-compose-dev.yml up -d keycloak
          docker-compose -f ./docker-compose-dev.yml build collectivo
          docker-compose -f ./docker-compose-dev.yml run --rm collectivo sh -c "python manage.py test && flake8"

